name: ChatGPT Auto-Reply

on:
  issues:
    types: [opened]

jobs:
  reply:
    runs-on: ubuntu-latest

    steps:
      - name: ChatGPT Issue Reply
        uses: actions/github-script@v6
        env:
          CHATGPT_KEY: ${{ secrets.chatgpt_key }}
        with:
          script: |
            const { Configuration, OpenAIApi } = require("openai");
            const openai = new OpenAIApi(
              new Configuration({ apiKey: process.env.CHATGPT_KEY })
            );
            const issueText = context.payload.issue.body;
            const completion = await openai.createChatCompletion({
              model: "gpt-4o-mini",
              messages: [
                { role: "system", content: "You are a helpful assistant." },
                { role: "user",   content: issueText }
              ]
            });
            await github.rest.issues.createComment({
              owner:        context.repo.owner,
              repo:         context.repo.repo,
              issue_number: context.payload.issue.number,
              body:         completion.data.choices[0].message.content
            });